apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ahmedelbendary/argocd-app-config.git
    targetRevision: HEAD
    path: micro-services/myapp/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true