apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ahmedelbendary/argocd-app-config.git
    targetRevision: HEAD
    path: micro-services/myapp/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-prod

  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true